# -*- coding: utf-8 -*-
"""Untitled0.ipynb

github link https://github.com/HaykInanc/auto_ru_parse


Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ZE0N9ZkllCHlBQWYF3i5I3ehm7qgaS1
"""


import sys


from pyspark.sql import SparkSession
import pyspark.sql.functions as F

spark = SparkSession.builder.appName('avto parse').getOrCreate()
filePath = sys.argv[1]+'/result.csv'


df = spark.read.csv(filePath, inferSchema=True, header=False)



split_column = F.split(df['_c1'], ' / ')

df.withColumn('engine_capacity',  F.regexp_replace( split_column.getItem(0) , r'[ а-яё]', '' ) ) \
  .withColumn('horsepower',       F.regexp_replace( split_column.getItem(1) , r'\D', '' ) ) \
  .withColumn('engine_type', split_column.getItem(2)) \
  .withColumn('price', F.regexp_replace(F.col('_c6'), r'\D', '' )) \
  .withColumn('milage', F.regexp_replace(F.col('_c8'), r'\D', '' )) \
  .withColumnRenamed('_c0', 'model') \
  .withColumnRenamed('_c2', 'transmission') \
  .withColumnRenamed('_c3', 'body_type') \
  .withColumnRenamed('_c4', 'drive_type') \
  .withColumnRenamed('_c5', 'color') \
  .withColumnRenamed('_c7', 'production_year') \
  .withColumnRenamed('_c9', 'auto_key') \
  .drop('_c1', '_c6', '_c8') \
  .write.csv(sys.argv[1]+'/result_01.csv', header = True)



